analytics:
  ua: ''
  gtag: 'G-JY1RD8J5KH'
  gtm: ''
  ga_prod: 'G-JY1RD8J5KH'
breadcrumbs:
  goal:
    - path: /
      label: general.home
    - path: /goals
      label: general.goals
  indicator:
    - path: /
      label: general.home
    - path: /goals
      label: general.goals
  post:
    - path: /
      label: general.home
    - path: /news
      label: menu.updates
cookie_consent_form:
  enabled: false
country:
  name: Central Asia 
  adjective: Central Asian
create_goals:
  previous_next_links: false
  goal_content_heading: ''
  goals: []
create_indicators:
  previous_next_links: false
create_pages:
  - filename: ''
    folder: /goals
    layout: goals
    title: general.goals
  - filename: ''
    folder: /reporting-status
    layout: reportingstatus
    title: status.reporting_status
  - filename: ''
    folder: /search
    layout: search
    title: search.search
custom_css: []
custom_js:
  - /assets/js/custom.js
data_edit_url: data
data_fields:
  units: ''
  series: ''
date_formats: []
disclaimer:
  phase: ''
  message: ''
  hidden: true
email_contacts:
  questions: mihail.peleah@undp.org
  suggestions: mihail.peleah@undp.org
  functional: mihail.peleah@undp.org
empty_metadata_placeholder: ''
empty_metadata_placeholder_sources: ''
environment: staging
footer_language_toggle: none
footer_menu:
  - path: /contact-us
    translation_key: menu.contact_us
  - path: 'https://twitter.com/UNDPEurasia'
    translation_key: general.twitter
  - path: /about/cookies-and-privacy/
    translation_key: menu.cookies
  - path: https://www.undp.org/
    translation_key: '<img src="https://central-asia-sdg-platform.github.io/www/assets/images/UNDP_logo_h40.png" alt="UNDP logo"> Implemented by UNDP '
  - path: https://european-union.europa.eu/index_en
    translation_key: '<img src="https://central-asia-sdg-platform.github.io/www/assets/images/EU_flag_h40.png" alt="EU flag"> Funded by EU '
frontpage_cards:
#  - title: frontpage.download_all
#    content: ''
#    include: components/download-all-data.html
#    button_label: ''
#    button_link: ''
#    rule_color: ''
  - title: European Union and SDGs in Central Asia 
    content: |
      The European Union (EU) plays a pivotal role in advancing Sustainable Development Goals (SDGs) throughout Central Asia, emphasizing the critical importance of investments for human prosperity and environmental stability across the region. By fostering cross-border collaboration and strategic partnerships, the EU actively promotes sustainable development initiatives that transcend geopolitical boundaries, addressing common challenges and opportunities shared among Central Asian nations. Notably, with the inclusion of Afghanistan in the broader Central Asian context, the EU's efforts become even more pertinent, aiming to stabilize conflict-affected regions while promoting economic resilience and social progress. Through targeted investments, capacity-building programs, and inclusive dialogue, the EU underscores the significance of collective action in achieving SDGs, ensuring a prosperous and sustainable future for generations to come in Central Asia and beyond.
    include: ''
    button_label: Read more
    button_link: 'https://www.eeas.europa.eu/eeas/projects_en?f%5B0%5D=project_site%3AKazakhstan&s=222'
    rule_color: ''
  - title: SDG Partnership 
    content: |
      Achieving SDGs requires whole-of-society approach, partenrship and collaboration. Learn how you could contribute to SDGs achievement in Central Asia
      * [Private sector](https://central-asia-sdg-platform.github.io/www/private-sector)
      * [CSO and NGOs](https://central-asia-sdg-platform.github.io/www/cso-and-ngo)
      * [Academia](https://central-asia-sdg-platform.github.io/www/academia)
      * [Parliaments](https://central-asia-sdg-platform.github.io/www/parliaments)
    include: ''
    button_label: Read more
    button_link: 'https://data.undp.org/sdg-push-diagnostic'
    rule_color: ''
  - title: SDG Push Diagnostics
    content: |
      SDG Push reimagines and recalibrates how we determine, interrogate and advance development interventions that put countries on more stable footing. The Diagnostic powers ‘Integrated SDG Insights‘ reports which provide a strong evidence-base and relevant insights to support national ambition at the SDG Summit 2023.
      [Overview of SDG Push diagnoistics for Central Asia](https://central-asia-sdg-platform.github.io/www/sdg-trends/)
    include: ''
    button_label: Read more
    button_link: 'https://data.undp.org/sdg-push-diagnostic'
    rule_color: ''
  - title: The 2023 SDG Summit
    content: |
      The 2023 SDG Summit will be convened on 18-19 September 2023, during the United Nations General Assembly high-level week. Heads of State and Government will gather at the United Nations Headquarters in New York to follow-up and review the implementation of the 2030 Agenda for Sustainable Development and the 17 Sustainable Development Goals (SDGs) . They will carry out a comprehensive review of the state of the SDGs, respond to the impact of multiple and interlocking crises facing the world, and provide high-level political guidance on transformative and accelerated actions leading up to the target year of 2030 for achieving the SDGs.
      The special edition of the report of the Secretary-General entitled “Progress towards the Sustainable Development Goals: Towards a Rescue Plan for People and Planet”, the [Advance Unedited version](https://hlpf.un.org/sites/default/files/2023-06/SDG%20Progress%20Report%20Special%20Edition_1_0.pdf) has been released.
    include: ''
    button_label: Read more
    button_link: 'https://www.un.org/en/conferences/SDGSummit2023'
    rule_color: ''
frontpage_goals_grid:
  title: Central Asia Sustainable Development Goal indicators
  description: Browse goals for indicator data
# [!] Revise for translation 
# frontpage_goals_grid:
#  title: frontpage.heading_short
#  description: frontpage.instructions_shorter
frontpage_introduction_banner:
  title: frontpage.intro_title
  description: frontpage.intro_body
goal_image_base: 'https://open-sdg.org/sdg-translations/assets/img/goals'
goal_image_extension: ''
goals_page:
  title: general.goals
  description: frontpage.instructions_shorter
graph_color_headline: '#004466'
graph_color_headline_high_contrast: '#55a6e5'
graph_color_set: accessible
graph_color_list: []
graph_color_number: 0
graph_title_from_series: false
header_language_toggle: dropdown
hide_empty_metadata: true
hide_single_series: true
hide_single_unit: true
indicator_config_form:
  enabled: true
  dropdowns: []
  repository_link: /tree/develop/indicator-config
  translation_link: ''
indicator_data_form:
  enabled: true
  repository_link: /tree/develop/data
indicator_metadata_form:
  enabled: true
  dropdowns: []
  repository_link: /tree/develop/meta
  translation_link: ''
  language: ''
  scopes:
    - national
#   - regional 
    - global
  exclude_fields: []
  translated: false
indicator_tabs:
  tab_1: ''
  tab_2: ''
  tab_3: ''
  tab_4: ''
languages:
  - en
  - ru
languages_public: []
logos: []
map_layers: []
map_options:
  disaggregation_controls: false
  minZoom: 5
  maxZoom: 10
  tileURL: ''
  tileOptions:
    id: ''
    accessToken: ''
    attribution: ''
  colorRange: chroma.brewer.BuGn
  noValueColor: '#f0f0f0'
  styleNormal:
    weight: 1
    opacity: 1
    fillOpacity: 0.7
    color: '#888888'
    dashArray: ''
  styleHighlighted:
    weight: 1
    opacity: 1
    fillOpacity: 0.7
    color: '#111111'
    dashArray: ''
  styleStatic:
    weight: 2
    opacity: 1
    fillOpacity: 0
    color: '#172d44'
    dashArray: '5,5'
menu:
  - path: /central-asia
    translation_key: about.centralasia
    dropdown: 
    - path: /central-asia-kaz
      translation_key: about.centralasia_kaz
    - path: /central-asia-kgz
      translation_key: about.centralasia_kgz
    - path: /central-asia-tjk
      translation_key: about.centralasia_tjk
    - path: /central-asia-tkm
      translation_key: about.centralasia_tkm
    - path: /central-asia-uzb
      translation_key: about.centralasia_uzb
    - path: /central-asia
      translation_key: about.centralasia
  - path: /partnership
    translation_key: menu-partnership.partnership
    dropdown:
    - path: /eu4sdgs-central-asia
      translation_key: menu-partnership.eu4sdgs-central-asia
    - path: /parliaments/
      translation_key: menu-partnership.parliaments
    - path: /private-sector
      translation_key: menu-partnership.private-sector
    - path: /academia
      translation_key: menu-partnership.academia
    - path: /cso-and-ngo
      translation_key: menu-partnership.cso-and-ngo
    - path: /vnr
      translation_key: menu-partnership.vnr
  - path: /sdg-actions
    translation_key: menu-actions.actions
    dropdown:
    - path: /goals
      translation_key: menu-actions.goals
    - path: /sdg-local
      translation_key: menu-actions.local
    - path: /policies
      translation_key: menu-actions.policies
    - path: /sdg-scenarios
      translation_key: menu-actions.scenarios
    - path: /systems
      translation_key: menu-actions.systems
    - path: /finances
      translation_key: menu-actions.finances
    - path: /hotspots
      translation_key: menu-actions.hotspots
    - path: /gender
      translation_key: menu-actions.gender
  - path: /sdg-stories
    translation_key: menu-stories.stories
#  - path: /about
#    translation_key: menu.about
#    dropdown: []
#  - path: /faq
#    translation_key: menu.faq
#    dropdown: []
#  - path: /news
#    translation_key: menu.updates
#    dropdown: []
metadata_edit_url: metadata
metadata_tabs:
  - scope: national
    title: indicator.national_metadata
    description: indicator.national_metadata_blurb
  - scope: global
    title: indicator.global_metadata
    description: indicator.global_metadata_blurb
  - scope: sources
    title: indicator.sources
    description: ''
news:
  category_links: false
progress_status:
  status_heading: ''
  status_types: []
remote_data_prefix: 'https://central-asia-sdg-platform.github.io/data'
reporting_status:
  title: status.reporting_status
  description: status.description
  disaggregation_tabs: false
  status_types:
    - value: notstarted
      label: status.no_data_available
      hide_on_goal_pages: false
    - value: complete
      label: status.reported_online
      hide_on_goal_pages: false
    - value: notapplicable
      label: status.not_applicable
      hide_on_goal_pages: false
repository_url_data: 'https://github.com/central-asia-sdg-platform/data/'
repository_url_site: 'https://github.com/central-asia-sdg-platform/www'
search_index_boost: []
search_index_extra_fields: []
site_config_form:
  enabled: true
  dropdowns: []
  repository_link: /tree/develop/_data
  translation_link: ''
time_series_attributes:
  - field: COMMENT_TS
    label: indicator.footnote
  - field: DATA_LAST_UPDATE
    label: metadata_fields.national_data_update_url
validate_indicator_config: false
validate_site_config: false
x_axis_label: ''
